model:
  name: "mobilenet_v2"
  num_classes: 9

client:
  count: 50
  resources:
    num_cpus: 24 #number of cpus per client
    num_gpus: 1  # Fraction of clients per gpu

dataset:
  name: "albertvillanova/medmnist-v2"  # dataset name on Hugging Face [ "BahaaEldin0/NIH-Chest-Xray-14", BahaaEldin0/NIH-Chest-Xray-14-with-Augmentation, "hf-vision/chest-xray-pneumonia", "marmal88/skin_cancer", SilpaCS/Augmented_alzheimer]
  subset: "bloodmnist"
  data_dir: "./data"
  seed: 123
  partitioner:
    name: "IiD"  # Type of data partition ["PathologicalPartitioner", "DirichletPartitioner", "Iid"]
    alpha: 0.1  # heterogeneity degree *DirichletPartitioner
    num_classes_per_partition: 2  # number of classes per partition *PathologicalPartitioner


strategy:
  name: "FedAvg"
  fraction_train_clients: 0.1
  config_fit:
    lr: 0.01
    momentum: 0.9
    local_epochs: 1
    local_batch_size: 32
  num_rounds: 100
  device: "cuda"  # "cuda" or "cpu"
  total_gpus: 1
  total_cpus: 32